language: java
jdk:
- oraclejdk8
env:
  global:
before_install:
install: mvn install -DskipTests=true -B
before_script:
script:
- echo ---------- deploy
- ". Setup/target/classes/content/deployOSSRH"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: pages
  on:
      branch: develop
