language: java
jdk:
- oraclejdk8
env:
  global:
install: mvn install -DskipTests=true -B
before_script:
- gpg --fast-import codesigning/codesigning.asc
script:
- echo ---------- deploy
- ". Setup/target/classes/content/deployOSSRH"
- echo ------- javadocs
- ". Setup/target/classes/content/createJavadocs"
- echo ------- nightly
- ". Setup/target/classes/content/createNightly"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: pages
  on:
      branch: develop
